---
# Kubernetes version
# apt-cache madison kubelet
version: "1.23.5"

# Load balancer IP
lba_ip: ""

# Pode network cdir
cidr: "172.20.0.0/16"

# CNI
cni: "weave"
cni_cdir_extra:
  flannel: "{{ cidr }}"
  weave: "{{ cidr }}"

# Kubeadm init logs file
init_file: kubeadm_init.log

# Others flags
reset: false
cluster: ""
