- name: Discover swap status
  shell: cat /proc/swaps | wc -l
  register: swap_out

- name: Disable swap if enabled
  shell: |
    dphys-swapfile swapoff
    dphys-swapfile uninstall
    systemctl disable dphys-swapfile
  when: swap_out.stdout != "1"

- name: Enable memory cgroup
  lineinfile:
    path: /boot/firmware/cmdline.txt
    # regexp: "^(.*) rootwait$"
    # line: '\1 rootwait cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
    # regexp: "^(.*) fixrtc$"
    # line: '\1 fixrtc cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
    regexp: "^(.*) splash$"
    line: '\1 splash cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
    backrefs: yes
  register: cmdline_modified

- name: Reboot host
  reboot:
  when: cmdline_modified.changed
