---
- name: Install Kubernetes
  include_tasks: install.yml
  tags:
    - install
    - upgrade

- name: Configure OS
  include_tasks: configure_os.yml
  tags:
    - install

- name: Discover node status
  include_tasks: discover.yml

- debug: var=node
- debug: var=cluster

- name: Create the cluster
  include_tasks: setup.yml
  when:
    - node == "primary-master"
    - cluster != "initialized"
  tags:
    - setup

- debug: var=node_ip
- debug: var=cluster

- name: Generate short-lived join token
  include_tasks: token.yml
  when:
    - node == "primary-master"
  tags:
    - token

- name: Join the cluster as master
  include_tasks: master_join.yml
  when:
    - node == "secondary-master"
    - cluster != "joined"
  tags:
    - join

- name: Join the cluster as worker
  include_tasks: worker_join.yml
  when:
    - node == "worker"
    - cluster != "joined"
  tags:
    - join

- name: Discover node status again once everyone has joined
  include_tasks: discover.yml

- name: Show cluster info
  shell: kubectl cluster-info
  register: cluster_info
  when:
    - node == "primary-master"
  tags:
    - status

- debug:
    var: cluster_info
  when:
    - node == "primary-master"
  tags:
    - status

- name: Show cluster nodes
  shell: kubectl get nodes
  register: status
  when:
    - node == "primary-master"
  tags:
    - status

#- debug: var=status
- debug:
    var: status
  when:
    - node == "primary-master"
  tags:
    - status
