---
- name: Install Kubernetes
  include_tasks: install.yml
  tags:
    - install
    - upgrade

- name: Configure OS
  include_tasks: configure_os.yml
  tags:
    - install

- name: Discover node status
  include_tasks: discover.yml
  tags:
    - install

- debug: var=node
- debug: var=cluster

- name: Create the cluster
  include_tasks: setup.yml
  when:
    - node == "primary-master"
    - cluster != "initialized"
  tags:
    - install
    - setup

- debug: var=node_ip
- debug: var=cluster

- name: Generate short-lived join token
  include_tasks: token.yml
  when:
    - node == "primary-master"
  tags:
    - install
    - token

- name: Join the cluster as master
  include_tasks: master_join.yml
  when:
    - node == "secondary-master"
    - cluster != "joined"
  tags:
    - install
    - join

- name: Join the cluster as worker
  include_tasks: worker_join.yml
  when:
    - node == "worker"
    - cluster != "joined"
  tags:
    - install
    - join

- name: Discover node status again once everyone has joined
  include_tasks: discover.yml
  tags:
    - install

- name: Show cluster status
  include_tasks: status.yml
  when:
    - node == "primary-master"
  tags:
    - install
    - status
