---
- name: Get token for master node join
  set_fact:
    join_cmd: "{{ hostvars['rpi-k8s-master-01']['master_join_cmd'] }}"

# Once https://github.com/kubernetes/kubeadm/issues/659 is resolved we can drop the unsafe flag and get/use the hash
- name: Join the cluster as master
  command: "{{ join_cmd }}"
  when:
    - join_cmd is defined and join_cmd != ""
  register: out

- debug: var=out
