---
- hosts: all
  tasks:
    - name: Clean /var/log
      shell: |
        find /var/log -type f -delete
      ignore_errors: yes
      tags:
        - clean

    - name: Clean apt cache
      shell: |
        rm -rf /var/cache/apt/*
        apt clean all
      ignore_errors: yes
      tags:
        - clean
