---
- hosts: all
  roles:
    - common
  tags:
    - common

- hosts: load_balancer
  roles:
    - haproxy
  tags:
    - lba

- hosts: master, worker
  roles:
    # NFS PV support
    - role: storage/nfs
      vars:
        master_ip: "10.11.13.21"
    # Longhorn PV support
    - storage/iscsi
    # OpenEBS PV support
    #- storrage/openebs
  tags:
    - storage

- hosts: master, worker
  roles:
    #- role: containerd
    - role: docker
      vars:
        version: "20.10.13"
    - role: kubernetes
      vars:
        version: "1.23.5"
        cidr: "10.14.0.0/16"
        cni: "weave"
  tags:
    - kubernetes
# - hosts: master
#   roles:
#   tags:
#     - addons
