---
- hosts: all
  roles:
    - common
  tags:
    - common

- hosts: lba
  roles:
    - docker
    - lba/haproxy
  tags:
    - lba

- hosts: master_pri, master_sec, worker
  roles:
    # NFS PV Support
    - storage/nfs
    # Longhorn PV Support
    - storage/iscsi
  tags:
    - storage

- hosts: master_pri, master_sec, worker
  roles:
    #- containerd
    - docker
    - kubernetes
  tags:
    - kubernetes
# - hosts: master_pri
#   roles:
#   tags:
#     - addons
