---
- name: Setup Server
  include_tasks: setup_server.yml
  when: node == "primary-master"

- name: Setup Clients
  include_tasks: setup_clients.yml
  when: node == "worker" or node == "secondary-master"
