- name: Install Client Packages
  apt:
    name: "{{ nfs_client_packages }}"
    state: present
  tags:
    - install

- debug: var=master_ip

- name: Mount the server dir
  mount:
    path: "{{ client_mount_dir }}"
    src: "{{ master_ip }}:{{ server_mount_dir }}"
    fstype: nfs
    opts: rw
    state: mounted
  ignore_errors: yes
